[package]
name = "ft_kalman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
csv = "1.3.1"
ctrlc = "3.4.4"
duct = "0.13.7"
